// generated by godefaultinstance -type=*MyOtherType -name=unexportedMyOtherType; DO NOT EDIT

package example
// A default instance of MyOtherType.
var unexportedMyOtherType *MyOtherType
// BothIn calls the BothIn method on unexportedMyOtherType.
func BothIn(xs ...int) bool { return unexportedMyOtherType.BothIn(xs...) }
// Max calls the Max method on unexportedMyOtherType.
func Max() int { return unexportedMyOtherType.Max() }
// Set calls the Set method on unexportedMyOtherType.
func Set(c, d int) { return unexportedMyOtherType.Set(c, d) }
